[project]
name = "aireloom"
version = "0.1.0"
description = "Python interface for the OpenAIRE Graph API"
authors = [
    {
        name = "Samuel Mok",
        email = "s.mok@utwente.nl"
    }

]
readme = "README.md"
license = {text= "MIT}
requires-python = ">=3.12"
dependencies = [
    "httpx"
]

[project.optional-dependencies]
lint = ["ruff"]
test = ["pytest"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
